/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type OriginalKey = "Cb" | "C" | "C#" | "Db" | "D" | "D#" | "Eb" | "E" | "E#" | "Fb" | "F" | "F#" | "Gb" | "G" | "G#" | "Ab" | "A" | "A#" | "Bb" | "B" | "B#";

export type Lines = Array<{
  _key: string;
} & Line>;

export type Line = {
  _type: "line";
  chords?: Array<{
    _key: string;
  } & Chord>;
  lyrics?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Chord = {
  _type: "chord";
  note?: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "-";
  flatSharp?: "" | "flat" | "sharp" | "doubleFlat" | "doubleSharp";
  modifier?: "" | "major" | "major-six" | "major-six-nine" | "major-seven" | "major-nine" | "major-eleven" | "major-thirteen" | "suspended-two" | "suspended-four" | "minor" | "minor-six" | "minor-seven" | "minor-nine" | "minor-eleven" | "minor-thirteen" | "minor-major-seven" | "dominant-seven" | "dominant-nine" | "dominant-thirteen" | "augmented" | "diminished" | "half-diminished";
  hardStop?: boolean;
};

export type Modifier = "" | "major" | "major-six" | "major-six-nine" | "major-seven" | "major-nine" | "major-eleven" | "major-thirteen" | "suspended-two" | "suspended-four" | "minor" | "minor-six" | "minor-seven" | "minor-nine" | "minor-eleven" | "minor-thirteen" | "minor-major-seven" | "dominant-seven" | "dominant-nine" | "dominant-thirteen" | "augmented" | "diminished" | "half-diminished";

export type FlatSharp = "" | "flat" | "sharp" | "doubleFlat" | "doubleSharp";

export type Note = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "-";

export type Song = {
  _id: string;
  _type: "song";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Array<{
    title?: "verse" | "pre-chorus" | "chorus" | "bridge" | "intro" | "outro" | "solo";
    lines?: Lines;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  originalKey?: OriginalKey;
  title?: string;
  slug?: Slug;
  artists?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "artist";
  }>;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | OriginalKey | Lines | Line | Chord | Modifier | FlatSharp | Note | Song | Artist | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../nextjs-songs-app/src/app/page.tsx
// Variable: HOME_SONG_QUERY
// Query: *[	_type == "song"] | order(title asc) {_id, title, slug}
export type HOME_SONG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;
// Variable: HOME_ARTIST_QUERY
// Query: *[	_type == "artist"] | order(title asc) {_id, title, slug}
export type HOME_ARTIST_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;

// Source: ../nextjs-songs-app/src/app/songs/[slug]/page.tsx
// Variable: SONG_QUERY
// Query: *[	_type == "song" &&	slug.current == $slug	][0]{	...,	title,	originalKey,	artists[]->{		slug,		title	},	sections}
export type SONG_QUERYResult = {
  _id: string;
  _type: "song";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections: Array<{
    title?: "bridge" | "chorus" | "intro" | "outro" | "pre-chorus" | "solo" | "verse";
    lines?: Lines;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }> | null;
  originalKey: OriginalKey | null;
  title: string | null;
  slug?: Slug;
  artists: Array<{
    slug: Slug | null;
    title: string | null;
  }> | null;
} | null;

// Source: ../nextjs-songs-app/src/app/artists/[slug]/page.tsx
// Variable: ARTIST_QUERY
// Query: *[	_type == "artist" &&	slug.current == $slug	][0]{	...,	title,	"songs": *[_type=='song' && references(^._id)]{ title, slug }}
export type ARTIST_QUERYResult = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  songs: Array<{
    title: string | null;
    slug: Slug | null;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n\t_type == \"song\"\n] | order(title asc) {_id, title, slug}": HOME_SONG_QUERYResult;
    "*[\n\t_type == \"artist\"\n] | order(title asc) {_id, title, slug}": HOME_ARTIST_QUERYResult;
    "*[\n\t_type == \"song\" &&\n\tslug.current == $slug\n\t][0]{\n\t...,\n\ttitle,\n\toriginalKey,\n\tartists[]->{\n\t\tslug,\n\t\ttitle\n\t},\n\tsections\n}": SONG_QUERYResult;
    "*[\n\t_type == \"artist\" &&\n\tslug.current == $slug\n\t][0]{\n\t...,\n\ttitle,\n\t\"songs\": *[_type=='song' && references(^._id)]{ title, slug }\n}": ARTIST_QUERYResult;
  }
}
